---
title: "Metodologia"
author: "Jan Borowski"
date: "03/06/2021"
output: html_document
---



### Methodology 

In our experiment, we want to use real data and use models in a similar way they may be used in commercial applications. Because of these two factors, we decide to use MIMIC-III database [@cyctay_mimica]. This base contains a very large quantity of real medical data and it's frequently used in machine learning oriented and other research. In our article, we use a subset of transformed features from this database directly correlated to patient health.

To create the Rashomon set we need to specify the exact task we want to test. To do this we examine already created articles about usage of this data in machine learning. We encountered many problems with reproducibility such as no longer supported or outdated code or badly optimized functions. Finally, we decide to use previous research about reproducibility of MIMIC studies [@cyctat artykułu z reproduktywalnościa]. In this article, the researchers examine several articles involving MIMIC and try to replicate their results. In our study, we choose one of the analyzed articles. 
The chosen study [@cyctak tamtego artykuły który wybralismy] concerns predicting death probability during ICU stays. More detailed explanations about feature generation and record selection can be found in the mentioned article. 

To perform our analysis we create extreme gradient boosting (farther referred to as XGB) models from package [@cytowanie pakietu]. We decide to use XGB because of its relative sensitivity to hyperparameters. Models are trained using random search with 1000 iterations and 3 folds. Data were split randomly to each fold. Hyperparameter space used in training can be found [@cytownaie artykuł z hypeparamerami]. This article contains recommended parameter spaces for this type of research. In the evaluation and selection of models, we use mean accuracy across folds and decide to choose a subset of models over a certain threshold. To examine how selected models work, we use feature importance plots with drop-out loss as a metric from package [@dalex] and partial dependency profiles (farther referred as PDP) also from the same package. 
